// Generated by node tools/inbetween-assets.mjs --write. Literal paths support standalone embedding.
export const HERO_INBETWEEN_ART = {
  "yi": {
    "heroId": "yi",
    "skin": null,
    "path": "assets/3d/fixed/inbetweens/yi-inbetweens-v1.webp",
    "width": 1266,
    "height": 1416,
    "roles": [
      "pass-a",
      "pass-b",
      "follow-through",
      "recover"
    ],
    "frames": [
      {
        "left": 24,
        "top": 24,
        "width": 246,
        "height": 296,
        "anchor": 0.56,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 350,
        "top": 24,
        "width": 211,
        "height": 297,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 655,
        "top": 24,
        "width": 214,
        "height": 298,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 962,
        "top": 24,
        "width": 231,
        "height": 298,
        "anchor": 0.44,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 24,
        "top": 370,
        "width": 256,
        "height": 301,
        "anchor": 0.62,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 350,
        "top": 370,
        "width": 223,
        "height": 303,
        "anchor": 0.49,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 655,
        "top": 370,
        "width": 226,
        "height": 305,
        "anchor": 0.51,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 962,
        "top": 370,
        "width": 249,
        "height": 302,
        "anchor": 0.38,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 24,
        "top": 723,
        "width": 278,
        "height": 313,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 350,
        "top": 723,
        "width": 257,
        "height": 311,
        "anchor": 0.45,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 655,
        "top": 723,
        "width": 259,
        "height": 312,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 962,
        "top": 723,
        "width": 280,
        "height": 314,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 24,
        "top": 1085,
        "width": 244,
        "height": 304,
        "anchor": 0.54,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 350,
        "top": 1085,
        "width": 226,
        "height": 302,
        "anchor": 0.49,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 655,
        "top": 1085,
        "width": 226,
        "height": 302,
        "anchor": 0.51,
        "anchorY": 1,
        "referenceHeight": 310
      },
      {
        "left": 962,
        "top": 1085,
        "width": 233,
        "height": 307,
        "anchor": 0.46,
        "anchorY": 1,
        "referenceHeight": 310
      }
    ]
  },
  "sejong": {
    "heroId": "sejong",
    "skin": null,
    "path": "assets/3d/fixed/inbetweens/sejong-inbetweens-v1.webp",
    "width": 1232,
    "height": 1460,
    "roles": [
      "pass-a",
      "pass-b",
      "follow-through",
      "recover"
    ],
    "frames": [
      {
        "left": 24,
        "top": 24,
        "width": 218,
        "height": 304,
        "anchor": 0.53,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 338,
        "top": 24,
        "width": 190,
        "height": 304,
        "anchor": 0.43,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 644,
        "top": 24,
        "width": 191,
        "height": 303,
        "anchor": 0.55,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 944,
        "top": 24,
        "width": 191,
        "height": 305,
        "anchor": 0.47,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 24,
        "top": 377,
        "width": 234,
        "height": 319,
        "anchor": 0.54,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 338,
        "top": 377,
        "width": 199,
        "height": 320,
        "anchor": 0.42,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 644,
        "top": 377,
        "width": 200,
        "height": 320,
        "anchor": 0.55,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 944,
        "top": 377,
        "width": 217,
        "height": 321,
        "anchor": 0.46,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 24,
        "top": 746,
        "width": 266,
        "height": 307,
        "anchor": 0.46,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 338,
        "top": 746,
        "width": 258,
        "height": 323,
        "anchor": 0.43,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 644,
        "top": 746,
        "width": 252,
        "height": 319,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 944,
        "top": 746,
        "width": 264,
        "height": 303,
        "anchor": 0.625,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 24,
        "top": 1117,
        "width": 208,
        "height": 319,
        "anchor": 0.54,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 338,
        "top": 1117,
        "width": 212,
        "height": 318,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 644,
        "top": 1117,
        "width": 206,
        "height": 317,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 305
      },
      {
        "left": 944,
        "top": 1117,
        "width": 203,
        "height": 316,
        "anchor": 0.46,
        "anchorY": 1,
        "referenceHeight": 305
      }
    ]
  },
  "eulji": {
    "heroId": "eulji",
    "skin": null,
    "path": "assets/3d/fixed/inbetweens/eulji-inbetweens-v1.webp",
    "width": 997,
    "height": 976,
    "roles": [
      "pass-a",
      "pass-b",
      "follow-through",
      "recover"
    ],
    "frames": [
      {
        "left": 24,
        "top": 24,
        "width": 154,
        "height": 198,
        "anchor": 0.65,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 277,
        "top": 24,
        "width": 158,
        "height": 199,
        "anchor": 0.49777,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 518,
        "top": 24,
        "width": 158,
        "height": 201,
        "anchor": 0.509059,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 767,
        "top": 24,
        "width": 156,
        "height": 200,
        "anchor": 0.36,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 24,
        "top": 273,
        "width": 165,
        "height": 198,
        "anchor": 0.63,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 277,
        "top": 273,
        "width": 159,
        "height": 199,
        "anchor": 0.49777,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 518,
        "top": 273,
        "width": 158,
        "height": 198,
        "anchor": 0.509059,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 767,
        "top": 273,
        "width": 166,
        "height": 198,
        "anchor": 0.35,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 24,
        "top": 520,
        "width": 205,
        "height": 187,
        "anchor": 0.424389,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 277,
        "top": 520,
        "width": 193,
        "height": 191,
        "anchor": 0.405173,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 518,
        "top": 520,
        "width": 201,
        "height": 194,
        "anchor": 0.557538,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 767,
        "top": 520,
        "width": 206,
        "height": 186,
        "anchor": 0.561561,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 24,
        "top": 762,
        "width": 164,
        "height": 180,
        "anchor": 0.563421,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 277,
        "top": 762,
        "width": 160,
        "height": 184,
        "anchor": 0.49777,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 518,
        "top": 762,
        "width": 168,
        "height": 190,
        "anchor": 0.509059,
        "anchorY": 1,
        "referenceHeight": 190
      },
      {
        "left": 767,
        "top": 762,
        "width": 167,
        "height": 179,
        "anchor": 0.452595,
        "anchorY": 1,
        "referenceHeight": 190
      }
    ]
  },
  "gang": {
    "heroId": "gang",
    "skin": null,
    "path": "assets/3d/fixed/inbetweens/gang-inbetweens-v1.webp",
    "width": 1333,
    "height": 1374,
    "roles": [
      "pass-a",
      "pass-b",
      "follow-through",
      "recover"
    ],
    "frames": [
      {
        "left": 24,
        "top": 24,
        "width": 278,
        "height": 291,
        "anchor": 0.543238,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 376,
        "top": 24,
        "width": 275,
        "height": 295,
        "anchor": 0.494672,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 699,
        "top": 24,
        "width": 254,
        "height": 297,
        "anchor": 0.458745,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 1016,
        "top": 24,
        "width": 280,
        "height": 290,
        "anchor": 0.485671,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 24,
        "top": 369,
        "width": 276,
        "height": 309,
        "anchor": 0.543238,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 376,
        "top": 369,
        "width": 275,
        "height": 311,
        "anchor": 0.494672,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 699,
        "top": 369,
        "width": 253,
        "height": 312,
        "anchor": 0.458745,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 1016,
        "top": 369,
        "width": 293,
        "height": 307,
        "anchor": 0.485671,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 24,
        "top": 729,
        "width": 304,
        "height": 274,
        "anchor": 0.466717,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 376,
        "top": 729,
        "width": 271,
        "height": 280,
        "anchor": 0.449052,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 699,
        "top": 729,
        "width": 269,
        "height": 273,
        "anchor": 0.53166,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 1016,
        "top": 729,
        "width": 283,
        "height": 276,
        "anchor": 0.526119,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 24,
        "top": 1057,
        "width": 268,
        "height": 289,
        "anchor": 0.543238,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 376,
        "top": 1057,
        "width": 266,
        "height": 292,
        "anchor": 0.494672,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 699,
        "top": 1057,
        "width": 246,
        "height": 293,
        "anchor": 0.458745,
        "anchorY": 1,
        "referenceHeight": 293
      },
      {
        "left": 1016,
        "top": 1057,
        "width": 240,
        "height": 288,
        "anchor": 0.485671,
        "anchorY": 1,
        "referenceHeight": 293
      }
    ]
  },
  "gwon": {
    "heroId": "gwon",
    "skin": null,
    "path": "assets/3d/fixed/inbetweens/gwon-inbetweens-v1.webp",
    "width": 1322,
    "height": 1351,
    "roles": [
      "pass-a",
      "pass-b",
      "follow-through",
      "recover"
    ],
    "frames": [
      {
        "left": 24,
        "top": 24,
        "width": 251,
        "height": 295,
        "anchor": 0.512638,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 380,
        "top": 24,
        "width": 223,
        "height": 297,
        "anchor": 0.509672,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 688,
        "top": 24,
        "width": 215,
        "height": 290,
        "anchor": 0.463326,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 991,
        "top": 24,
        "width": 245,
        "height": 296,
        "anchor": 0.460919,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 24,
        "top": 369,
        "width": 247,
        "height": 306,
        "anchor": 0.512638,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 380,
        "top": 369,
        "width": 216,
        "height": 306,
        "anchor": 0.509672,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 688,
        "top": 369,
        "width": 209,
        "height": 299,
        "anchor": 0.463326,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 991,
        "top": 369,
        "width": 238,
        "height": 305,
        "anchor": 0.460919,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 24,
        "top": 723,
        "width": 308,
        "height": 265,
        "anchor": 0.44644,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 380,
        "top": 723,
        "width": 260,
        "height": 264,
        "anchor": 0.47,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 688,
        "top": 723,
        "width": 255,
        "height": 266,
        "anchor": 0.552449,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 991,
        "top": 723,
        "width": 307,
        "height": 268,
        "anchor": 0.537893,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 24,
        "top": 1039,
        "width": 278,
        "height": 288,
        "anchor": 0.512638,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 380,
        "top": 1039,
        "width": 254,
        "height": 278,
        "anchor": 0.509672,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 688,
        "top": 1039,
        "width": 247,
        "height": 280,
        "anchor": 0.463326,
        "anchorY": 1,
        "referenceHeight": 285
      },
      {
        "left": 991,
        "top": 1039,
        "width": 275,
        "height": 283,
        "anchor": 0.460919,
        "anchorY": 1,
        "referenceHeight": 285
      }
    ]
  },
  "gwak": {
    "heroId": "gwak",
    "skin": null,
    "path": "assets/3d/fixed/inbetweens/gwak-inbetweens-v1.webp",
    "width": 1045,
    "height": 1291,
    "roles": [
      "pass-a",
      "pass-b",
      "follow-through",
      "recover"
    ],
    "frames": [
      {
        "left": 24,
        "top": 24,
        "width": 183,
        "height": 277,
        "anchor": 0.492593,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 295,
        "top": 24,
        "width": 169,
        "height": 279,
        "anchor": 0.452126,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 547,
        "top": 24,
        "width": 165,
        "height": 277,
        "anchor": 0.65,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 799,
        "top": 24,
        "width": 167,
        "height": 276,
        "anchor": 0.495042,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 24,
        "top": 351,
        "width": 164,
        "height": 276,
        "anchor": 0.492593,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 295,
        "top": 351,
        "width": 145,
        "height": 276,
        "anchor": 0.452126,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 547,
        "top": 351,
        "width": 147,
        "height": 277,
        "anchor": 0.61,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 799,
        "top": 351,
        "width": 158,
        "height": 276,
        "anchor": 0.495042,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 24,
        "top": 676,
        "width": 223,
        "height": 280,
        "anchor": 0.434951,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 295,
        "top": 676,
        "width": 204,
        "height": 278,
        "anchor": 0.440223,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 547,
        "top": 676,
        "width": 204,
        "height": 277,
        "anchor": 0.552396,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 799,
        "top": 676,
        "width": 222,
        "height": 279,
        "anchor": 0.558612,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 24,
        "top": 1004,
        "width": 189,
        "height": 262,
        "anchor": 0.492593,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 295,
        "top": 1004,
        "width": 180,
        "height": 263,
        "anchor": 0.452126,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 547,
        "top": 1004,
        "width": 180,
        "height": 262,
        "anchor": 0.52941,
        "anchorY": 1,
        "referenceHeight": 270
      },
      {
        "left": 799,
        "top": 1004,
        "width": 178,
        "height": 262,
        "anchor": 0.495042,
        "anchorY": 1,
        "referenceHeight": 270
      }
    ]
  },
  "ahn": {
    "heroId": "ahn",
    "skin": null,
    "path": "assets/3d/fixed/inbetweens/ahn-inbetweens-v1.webp",
    "width": 1030,
    "height": 1236,
    "roles": [
      "pass-a",
      "pass-b",
      "follow-through",
      "recover"
    ],
    "frames": [
      {
        "left": 24,
        "top": 24,
        "width": 162,
        "height": 260,
        "anchor": 0.52479,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 284,
        "top": 24,
        "width": 174,
        "height": 264,
        "anchor": 0.44,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 544,
        "top": 24,
        "width": 158,
        "height": 265,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 793,
        "top": 24,
        "width": 158,
        "height": 258,
        "anchor": 0.473755,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 24,
        "top": 337,
        "width": 157,
        "height": 256,
        "anchor": 0.52479,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 284,
        "top": 337,
        "width": 172,
        "height": 255,
        "anchor": 0.46,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 544,
        "top": 337,
        "width": 170,
        "height": 257,
        "anchor": 0.5,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 793,
        "top": 337,
        "width": 155,
        "height": 255,
        "anchor": 0.473755,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 24,
        "top": 642,
        "width": 212,
        "height": 249,
        "anchor": 0.428626,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 284,
        "top": 642,
        "width": 212,
        "height": 258,
        "anchor": 0.427352,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 544,
        "top": 642,
        "width": 201,
        "height": 257,
        "anchor": 0.531864,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 793,
        "top": 642,
        "width": 213,
        "height": 250,
        "anchor": 0.570551,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 24,
        "top": 948,
        "width": 168,
        "height": 257,
        "anchor": 0.52479,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 284,
        "top": 948,
        "width": 181,
        "height": 263,
        "anchor": 0.525213,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 544,
        "top": 948,
        "width": 181,
        "height": 264,
        "anchor": 0.461072,
        "anchorY": 1,
        "referenceHeight": 254.5
      },
      {
        "left": 793,
        "top": 948,
        "width": 168,
        "height": 255,
        "anchor": 0.473755,
        "anchorY": 1,
        "referenceHeight": 254.5
      }
    ]
  },
  "dangun": {
    "heroId": "dangun",
    "skin": null,
    "path": "assets/3d/fixed/inbetweens/dangun-inbetweens-v1.webp",
    "width": 1058,
    "height": 1127,
    "roles": [
      "pass-a",
      "pass-b",
      "follow-through",
      "recover"
    ],
    "frames": [
      {
        "left": 24,
        "top": 24,
        "width": 171,
        "height": 245,
        "anchor": 0.527138,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 301,
        "top": 24,
        "width": 169,
        "height": 241,
        "anchor": 0.45,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 556,
        "top": 24,
        "width": 164,
        "height": 242,
        "anchor": 0.54,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 809,
        "top": 24,
        "width": 172,
        "height": 245,
        "anchor": 0.460881,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 24,
        "top": 317,
        "width": 182,
        "height": 244,
        "anchor": 0.527138,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 301,
        "top": 317,
        "width": 169,
        "height": 244,
        "anchor": 0.46,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 556,
        "top": 317,
        "width": 169,
        "height": 244,
        "anchor": 0.52,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 809,
        "top": 317,
        "width": 183,
        "height": 244,
        "anchor": 0.460881,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 24,
        "top": 609,
        "width": 229,
        "height": 216,
        "anchor": 0.478438,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 301,
        "top": 609,
        "width": 207,
        "height": 218,
        "anchor": 0.432054,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 556,
        "top": 609,
        "width": 205,
        "height": 217,
        "anchor": 0.551343,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 809,
        "top": 609,
        "width": 225,
        "height": 218,
        "anchor": 0.523123,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 24,
        "top": 875,
        "width": 179,
        "height": 224,
        "anchor": 0.527138,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 301,
        "top": 875,
        "width": 180,
        "height": 228,
        "anchor": 0.570995,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 556,
        "top": 875,
        "width": 176,
        "height": 227,
        "anchor": 0.412022,
        "anchorY": 1,
        "referenceHeight": 244
      },
      {
        "left": 809,
        "top": 875,
        "width": 185,
        "height": 225,
        "anchor": 0.460881,
        "anchorY": 1,
        "referenceHeight": 244
      }
    ]
  }
};
