// Generated by tools/tactic-assets.mjs --record. Irregular alpha bounds, not grid UVs.
export const TACTIC_ART={
  "path": "assets/3d/fixed/tactic-signatures-v1.webp",
  "width": 1122,
  "height": 1402,
  "padding": 12,
  "frames": [
    {
      "key": "skill-singijeon",
      "left": 31,
      "top": 61,
      "width": 273,
      "height": 241
    },
    {
      "key": "skill-bongsu",
      "left": 327,
      "top": 5,
      "width": 233,
      "height": 298
    },
    {
      "key": "skill-uibyeong",
      "left": 583,
      "top": 36,
      "width": 282,
      "height": 271
    },
    {
      "key": "skill-bigyeok",
      "left": 888,
      "top": 38,
      "width": 218,
      "height": 270
    },
    {
      "key": "skill-gunryang",
      "left": 30,
      "top": 323,
      "width": 260,
      "height": 241
    },
    {
      "key": "skill-cheonja",
      "left": 309,
      "top": 326,
      "width": 256,
      "height": 234
    },
    {
      "key": "skill-donguibogam",
      "left": 575,
      "top": 322,
      "width": 270,
      "height": 244
    },
    {
      "key": "skill-hanpa",
      "left": 862,
      "top": 329,
      "width": 248,
      "height": 237
    },
    {
      "key": "combo-yi_sejong",
      "left": 17,
      "top": 580,
      "width": 279,
      "height": 263
    },
    {
      "key": "combo-eulji_gang",
      "left": 320,
      "top": 591,
      "width": 237,
      "height": 254
    },
    {
      "key": "combo-gwak_gwon",
      "left": 574,
      "top": 579,
      "width": 278,
      "height": 273
    },
    {
      "key": "combo-gwon_yi",
      "left": 872,
      "top": 592,
      "width": 237,
      "height": 255
    },
    {
      "key": "combo-eulji_sejong",
      "left": 21,
      "top": 870,
      "width": 272,
      "height": 241
    },
    {
      "key": "combo-gang_yi",
      "left": 311,
      "top": 856,
      "width": 246,
      "height": 267
    },
    {
      "key": "combo-ahn_sejong",
      "left": 574,
      "top": 876,
      "width": 260,
      "height": 231
    },
    {
      "key": "combo-dangun_eulji",
      "left": 870,
      "top": 860,
      "width": 232,
      "height": 256
    },
    {
      "key": "combo-ahn_yi",
      "left": 18,
      "top": 1138,
      "width": 267,
      "height": 237
    },
    {
      "key": "combo-dangun_sejong",
      "left": 306,
      "top": 1123,
      "width": 257,
      "height": 255
    },
    {
      "key": "combo-generic",
      "left": 581,
      "top": 1127,
      "width": 266,
      "height": 244
    },
    {
      "key": "attack-slash",
      "left": 857,
      "top": 1133,
      "width": 254,
      "height": 232
    }
  ]
};
