#!/usr/bin/env node
// Inspect/group connected alpha components. Never repaint the generated art.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {sharp} from './sprite-pose-inspector.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const source='assets/3d/fixed/source/hero-signatures-v1.png',delivery='assets/3d/fixed/hero-signatures-v1.webp';
const keys=['yi-skill','yi-ult','sejong-skill','sejong-ult','eulji-skill','eulji-ult','gang-skill','gang-ult','gwon-skill','gwon-ult','gwak-skill','gwak-ult','ahn-skill','ahn-ult','dangun-skill','dangun-ult'];
if(process.argv.includes('--prepare'))await sharp(path.join(root,source)).webp({quality:92,alphaQuality:100,effort:6}).toFile(path.join(root,delivery));
const {data,info}=await sharp(path.join(root,source)).ensureAlpha().raw().toBuffer({resolveWithObject:true});
const {width,height}=info,labels=new Int32Array(width*height),queue=new Int32Array(width*height),components=[];
for(let start=0;start<labels.length;start++){
  if(labels[start]||data[start*4+3]<16)continue;
  const id=components.length+1;let head=0,tail=1,left=width,top=height,right=-1,bottom=-1,sumX=0,sumY=0,visible=0;
  queue[0]=start;labels[start]=id;
  while(head<tail){
    const at=queue[head++],x=at%width,y=Math.floor(at/width);left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);sumX+=x;sumY+=y;if(data[at*4+3]>=41)visible++;
    for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){
      const xx=x+dx,yy=y+dy;if(xx<0||xx>=width||yy<0||yy>=height)continue;
      const next=yy*width+xx;if(!labels[next]&&data[next*4+3]>=16){labels[next]=id;queue[tail++]=next;}
    }
  }
  const cx=sumX/tail,cy=sumY/tail,cell=Math.min(3,Math.floor(cy/height*4))*4+Math.min(3,Math.floor(cx/width*4));
  components.push({id,left,top,right,bottom,cell,visible,count:tail});
}
const frames=keys.map((key,cell)=>{
  const own=components.filter(c=>c.cell===cell&&c.visible>0);assert.ok(own.some(c=>c.count>2000),key+' must have a visible motif');
  const left=Math.min(...own.map(c=>c.left)),top=Math.min(...own.map(c=>c.top)),right=Math.max(...own.map(c=>c.right)),bottom=Math.max(...own.map(c=>c.bottom));
  return {key,left,top,width:right-left+1,height:bottom-top+1};
});
const coverage=new Uint8Array(width*height),foreignVisiblePixels=frames.map((f,cell)=>{
  let foreign=0;for(let y=f.top;y<f.top+f.height;y++)for(let x=f.left;x<f.left+f.width;x++){
    const p=y*width+x;coverage[p]++;if(data[p*4+3]>=41&&components[labels[p]-1]?.cell!==cell)foreign++;
  }return foreign;
});
let uncoveredVisiblePixels=0,duplicateVisiblePixels=0,outerBorderVisiblePixels=0;
for(let p=0;p<coverage.length;p++)if(data[p*4+3]>=41){
  if(!coverage[p])uncoveredVisiblePixels++;if(coverage[p]>1)duplicateVisiblePixels++;
  const x=p%width,y=Math.floor(p/width);if(x===0||y===0||x===width-1||y===height-1)outerBorderVisiblePixels++;
}
assert.ok(foreignVisiblePixels.every(n=>n===0),'Motif rectangles contain foreign visible pixels');
assert.equal(uncoveredVisiblePixels,0);assert.equal(duplicateVisiblePixels,0);assert.equal(outerBorderVisiblePixels,0);
const encoded=await sharp(path.join(root,delivery)).ensureAlpha().raw().toBuffer({resolveWithObject:true});
assert.equal(encoded.info.width,width);assert.equal(encoded.info.height,height);
let alphaDifferences=0;for(let p=3;p<data.length;p+=4)if(data[p]!==encoded.data[p])alphaDifferences++;
assert.equal(alphaDifferences,0);
const layout={path:delivery,width,height,padding:12,frames};
const report={date:'2026-10-11',source,delivery,generation:'built-in imagegen; original PNG and full prompt preserved',processing:'WebP compression and alpha-component analysis only; no repainting',motifs:keys.length,width,height,bytes:(await fs.stat(path.join(root,delivery))).size,foreignVisiblePixels,uncoveredVisiblePixels,duplicateVisiblePixels,outerBorderVisiblePixels,alphaDifferences,frames};
assert.ok(report.bytes<900000,'Signature atlas must fit the art budget');
if(process.argv.includes('--record')){
  await fs.writeFile(path.join(root,'src/3d/signature-data.js'),'// Generated by tools/signature-assets.mjs --record. Irregular alpha bounds, not grid UVs.\nexport const SIGNATURE_ART='+JSON.stringify(layout,null,2)+';\n');
  await fs.writeFile(path.join(root,'docs/SKILL_SIGNATURE_ASSET_VALIDATION.json'),JSON.stringify(report,null,2)+'\n');
}else{
  const {SIGNATURE_ART}=await import('../src/3d/signature-data.js');assert.deepEqual(layout,SIGNATURE_ART);
}
console.log(JSON.stringify(report,null,2));
